/* config.h — generated by CMake from config.h.cmake.in          */
/* Do not edit directly; run cmake -S . -B <builddir> to refresh  */

/* the SVN version of Archive.cc */
#define ARCHIVE_SVN "cmake"

/* How and when GNU APL was configured */
#define BUILDTAG PACKAGE_NAME, PACKAGE_VERSION " / cmake", "2026-04-27 23:03:39 UTC", "macOS 20 core Apple M1 Ultra", "cmake -S . -B <builddir>"

/* Define to 1 iff pthread_setaffinity_np() is available */
/* #undef HAVE_AFFINITY_NP */

/* Define to 1 if you have the 'alarm' function. */
#define HAVE_ALARM 1

/* Define to 1 iff <curses.h> is present */
/* #undef HAVE_CURSES_H */

/* Define to 1 if you have the <dirent.h> header file. */
#define HAVE_DIRENT_H 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the 'dup2' function. */
#define HAVE_DUP2 1

/* Define to 1 if you have the <execinfo.h> header file. */
#define HAVE_EXECINFO_H 1

/* Define to 1 if you have the <ext/atomicity.h> header file. */
/* #undef HAVE_EXT_ATOMICITY_H */

/* Define to 1 if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* Define to 1 if you have the <fenv.h> header file. */
#define HAVE_FENV_H 1

/* Define to 1 if you have the <fftw3.h> header file. */
/* #undef HAVE_FFTW3_H */

/* Define to 1 if you have the 'floor' function. */
#define HAVE_FLOOR 1

/* Define to 1 if you have the 'fork' function. */
#define HAVE_FORK 1

/* Define to 1 if you have the 'getcwd' function. */
#define HAVE_GETCWD 1

/* Define to 1 if you have the 'gethostbyname' function. */
#define HAVE_GETHOSTBYNAME 1

/* Define to 1 if you have the 'getpagesize' function. */
#define HAVE_GETPAGESIZE 1

/* Define to 1 iff the OS has gettimeofday() */
#define HAVE_GETTIMEOFDAY 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 iff ioctl(fd, TIOCGWINSZ, ...) is available */
#define HAVE_IOCTL_TIOCGWINSZ 1

/* Define to 1 if you have the 'atomicity' library (-latomicity). */
/* #undef HAVE_LIBATOMICITY */

/* Define to 1 if you have the 'c' library (-lc). */
/* #undef HAVE_LIBC */

/* Define to 1 if you have the 'cairo' library (-lcairo). */
#define HAVE_LIBCAIRO 1

/* Define to 1 if you have the 'curses' library (-lcurses). */
#define HAVE_LIBCURSES 1

/* Define to 1 if you have the 'dl' library (-ldl). */
#define HAVE_LIBDL 1

/* Define to 1 if you have the 'fftw3' library (-lfftw3). */
#define HAVE_LIBFFTW3 1

/* Define to 1 if you have the 'gdk-3' library (-lgdk-3). */
#define HAVE_LIBGDK_3 1

/* Define to 1 if you have the 'gsl' library (-lgsl). */
/* #undef HAVE_LIBGSL */

/* Define to 1 if you have the 'gslcblas' library (-lgslcblas). */
/* #undef HAVE_LIBGSLCBLAS */

/* Define to 1 if you have the 'gtk-3' library (-lgtk-3). */
#define HAVE_LIBGTK_3 1

/* Define to 1 if you have the 'm' library (-lm). */
#define HAVE_LIBM 1

/* Define to 1 if you have the 'ncurses' library (-lncurses). */
#define HAVE_LIBNCURSES 1

/* Define to 1 if you have the 'nsl' library (-lnsl). */
/* #undef HAVE_LIBNSL */

/* Define to 1 if you have the 'pcre2-32' library (-lpcre2-32). */
#define HAVE_LIBPCRE2_32 1

/* Define to 1 if you have the 'png' library (-lpng). */
#define HAVE_LIBPNG 1

/* Define to 1 if you have the <libpng16/png.h> header file. */
/* #undef HAVE_LIBPNG16_PNG_H */

/* Define to 1 if you have the 'pthread' library (-lpthread). */
#define HAVE_LIBPTHREAD 1

/* Define to 1 if you have the 'socket' library (-lsocket). */
/* #undef HAVE_LIBSOCKET */

/* Define to 1 if you have the 'tinfo' library (-ltinfo). */
/* #undef HAVE_LIBTINFO */

/* Define to 1 if you have the 'X11' library (-lX11). */
/* #undef HAVE_LIBX11 */

/* Define to 1 if you have the 'X11-xcb' library (-lX11-xcb). */
/* #undef HAVE_LIBX11_XCB */

/* Define to 1 if you have the 'xcb' library (-lxcb). */
/* #undef HAVE_LIBXCB */

/* Define to 1 if you have the 'z' library (-lz). */
#define HAVE_LIBZ 1

/* Define to 1 if you have the <limits.h> header file. */
#define HAVE_LIMITS_H 1

/* Define to 1 if you have the <locale.h> header file. */
#define HAVE_LOCALE_H 1

/* Define to 1 if your system has a GNU libc compatible 'malloc' function. */
#define HAVE_MALLOC 1

/* Define to 1 if you have the <malloc.h> header file. */
/* #undef HAVE_MALLOC_H */

/* Define to 1 if you have the 'memset' function. */
#define HAVE_MEMSET 1

/* Define to 1 if you have the <minix/config.h> header file. */
/* #undef HAVE_MINIX_CONFIG_H */

/* Define to 1 if you have the 'mkdir' function. */
#define HAVE_MKDIR 1

/* Define to 1 if you have a working 'mmap' system call. */
#define HAVE_MMAP 1

/* Define to 1 if you have the 'modf' function. */
#define HAVE_MODF 1

/* Define to 1 if you have the 'munmap' function. */
#define HAVE_MUNMAP 1

/* Define to 1 iff <ncurses.h> is present */
#define HAVE_NCURSES_H 1

/* Define to 1 if you have the <netdb.h> header file. */
#define HAVE_NETDB_H 1

/* Define to 1 if you have the <netinet/in.h> header file. */
#define HAVE_NETINET_IN_H 1

/* Define to 1 if you have the <netinet/tcp.h> header file. */
#define HAVE_NETINET_TCP_H 1

/* Define to 1 iff OSAtomicAdd32Barrier() is available */
#define HAVE_OSX_ATOMIC 1

/* Define to 1 if PostgreSQL libraries are available */
#define HAVE_POSTGRESQL 1

/* Define to 1 if you have the 'pow' function. */
#define HAVE_POW 1

/* Define to 1 iff pthread_setname_np() is available */
/* #undef HAVE_PTHREAD_SETNAME_NP */

/* Define to 1 iff the CPU has rdtsc opcode */
/* #undef HAVE_RDTSC */

/* Define to 1 if you have the 'realpath' function. */
#define HAVE_REALPATH 1

/* Define to 1 if you have the 'rint' function. */
#define HAVE_RINT 1

/* Define to 1 if you have the 'rmdir' function. */
#define HAVE_RMDIR 1

/* Define to 1 if you have the 'select' function. */
#define HAVE_SELECT 1

/* Define to 1 iff sem_init() works */
#define HAVE_SEM_INIT 1

/* Define to 1 if you have the 'setenv' function. */
#define HAVE_SETENV 1

/* Define to 1 if you have the 'setlocale' function. */
#define HAVE_SETLOCALE 1

/* Define to 1 if you have the 'socket' function. */
#define HAVE_SOCKET 1

/* Define to 1 iff atomic_add_32_nv() is available */
/* #undef HAVE_SOLARIS_ATOMIC */

/* Define to 1 if libsqlite3 library is available */
#define HAVE_SQLITE3 1

/* Define to 1 if you have the 'sqrt' function. */
#define HAVE_SQRT 1

/* Define to 1 if 'st_blksize stat.st_rdev' is a member of 'stat'. */
#define HAVE_STAT_ST_BLKSIZE_STAT_ST_RDEV 1

/* Define to 1 if stdbool.h conforms to C99. */
#define HAVE_STDBOOL_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdio.h> header file. */
#define HAVE_STDIO_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the 'strcasecmp' function. */
#define HAVE_STRCASECMP 1

/* Define to 1 if you have the 'strchr' function. */
#define HAVE_STRCHR 1

/* Define to 1 if you have the 'strdup' function. */
#define HAVE_STRDUP 1

/* Define to 1 if you have the 'strerror' function. */
#define HAVE_STRERROR 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the 'strncasecmp' function. */
#define HAVE_STRNCASECMP 1

/* Define to 1 if you have the 'strndup' function. */
#define HAVE_STRNDUP 1

/* Define to 1 if you have the 'strrchr' function. */
#define HAVE_STRRCHR 1

/* Define to 1 if you have the 'strstr' function. */
#define HAVE_STRSTR 1

/* Define to 1 if you have the 'strtol' function. */
#define HAVE_STRTOL 1

/* Define to 1 if 'st_blocks' is a member of 'struct stat'. */
/* #undef HAVE_STRUCT_STAT_ST_BLOCKS */

/* Deprecated alias for HAVE_STRUCT_STAT_ST_BLOCKS */
/* #undef HAVE_ST_BLOCKS */

/* Define to 1 if you have the <sys/fcntl.h> header file. */
#define HAVE_SYS_FCNTL_H 1

/* Define to 1 if you have the <sys/ioctl.h> header file. */
#define HAVE_SYS_IOCTL_H 1

/* Define to 1 if you have the <sys/mman.h> header file. */
#define HAVE_SYS_MMAN_H 1

/* Define to 1 if you have the <sys/param.h> header file. */
#define HAVE_SYS_PARAM_H 1

/* Define to 1 if you have the <sys/resource.h> header file. */
#define HAVE_SYS_RESOURCE_H 1

/* Define to 1 if you have the <sys/select.h> header file. */
#define HAVE_SYS_SELECT_H 1

/* Define to 1 if you have the <sys/socket.h> header file. */
#define HAVE_SYS_SOCKET_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <sys/un.h> header file. */
#define HAVE_SYS_UN_H 1

/* Define to 1 if you have the <sys/wait.h> header file. */
#define HAVE_SYS_WAIT_H 1

/* Define to 1 if you have the <termios.h> header file. */
#define HAVE_TERMIOS_H 1

/* Define to 1 iff <term.h> is present */
#define HAVE_TERM_H 1

/* Define to 1 if you have the 'uname' function. */
#define HAVE_UNAME 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the <utmpx.h> header file. */
#define HAVE_UTMPX_H 1

/* Define to 1 if you have the <vector> header file. */
#define HAVE_VECTOR 1

/* Define to 1 if you have the 'vfork' function. */
#define HAVE_VFORK 1

/* Define to 1 if you have the <vfork.h> header file. */
/* #undef HAVE_VFORK_H */

/* Define to 1 if you have the <wchar.h> header file. */
#define HAVE_WCHAR_H 1

/* Define to 1 if you have the <windows.h> header file. */
/* #undef HAVE_WINDOWS_H */

/* Define to 1 if you have the <winsock2.h> header file. */
/* #undef HAVE_WINSOCK2_H */

/* Define to 1 if 'fork' works. */
#define HAVE_WORKING_FORK 1

/* Define to 1 if 'vfork' works. */
#define HAVE_WORKING_VFORK 1

/* Define to 1 if you have the <X11/XKBlib.h> header file. */
/* #undef HAVE_X11_XKBLIB_H */

/* Define to 1 if you have the <X11/Xlib.h> header file. */
/* #undef HAVE_X11_XLIB_H */

/* Define to 1 if you have the <X11/Xlib-xcb.h> header file. */
/* #undef HAVE_X11_XLIB_XCB_H */

/* Define to 1 if you have the <X11/Xutil.h> header file. */
/* #undef HAVE_X11_XUTIL_H */

/* Define to 1 if you have the <xcb/xcb.h> header file. */
/* #undef HAVE_XCB_XCB_H */

/* Define to 1 if you have the <zlib.h> header file. */
#define HAVE_ZLIB_H 1

/* Define to 1 if the system has the type '_Bool'. */
/* #undef HAVE__BOOL */

/* Libtool objects sub-directory (CMake: always .libs/ for compat) */
#define LT_OBJDIR ".libs/"

/* Compiling for MINGW */
#define MINGW_SRC 0

/* Name of package */
#define PACKAGE "apl"

/* Bug report address */
#define PACKAGE_BUGREPORT "bug-apl@gnu.org"

/* Full name of package */
#define PACKAGE_NAME "GNU APL"

/* Full name and version */
#define PACKAGE_STRING "GNU APL 2.0"

/* Short package name */
#define PACKAGE_TARNAME "apl"

/* Home page */
#define PACKAGE_URL "https://www.gnu.org/software/apl/"

/* Version of package */
#define PACKAGE_VERSION "2.0"

/* Standard C89 headers exist */
#define STDC_HEADERS 1

/* Version number */
#define VERSION "2.0"

/* System-extension macros (mirrors AC_USE_SYSTEM_EXTENSIONS) */
#ifndef _ALL_SOURCE
# define _ALL_SOURCE 1
#endif
#ifndef _COSMO_SOURCE
# define _COSMO_SOURCE 1
#endif
#ifndef _DARWIN_C_SOURCE
# define _DARWIN_C_SOURCE 1
#endif
#ifndef __EXTENSIONS__
# define __EXTENSIONS__ 1
#endif
#ifndef _GNU_SOURCE
# define _GNU_SOURCE 1
#endif
#ifndef _HPUX_ALT_XOPEN_SOCKET_API
# define _HPUX_ALT_XOPEN_SOCKET_API 1
#endif
#ifndef _MINIX
/* # undef _MINIX */
#endif
#ifndef _NETBSD_SOURCE
# define _NETBSD_SOURCE 1
#endif
#ifndef _OPENBSD_SOURCE
# define _OPENBSD_SOURCE 1
#endif
#ifndef _POSIX_SOURCE
/* # undef _POSIX_SOURCE */
#endif
#ifndef _POSIX_1_SOURCE
/* # undef _POSIX_1_SOURCE */
#endif
#ifndef _POSIX_PTHREAD_SEMANTICS
# define _POSIX_PTHREAD_SEMANTICS 1
#endif
#ifndef __STDC_WANT_IEC_60559_ATTRIBS_EXT__
# define __STDC_WANT_IEC_60559_ATTRIBS_EXT__ 1
#endif
#ifndef __STDC_WANT_IEC_60559_BFP_EXT__
# define __STDC_WANT_IEC_60559_BFP_EXT__ 1
#endif
#ifndef __STDC_WANT_IEC_60559_DFP_EXT__
# define __STDC_WANT_IEC_60559_DFP_EXT__ 1
#endif
#ifndef __STDC_WANT_IEC_60559_EXT__
# define __STDC_WANT_IEC_60559_EXT__ 1
#endif
#ifndef __STDC_WANT_IEC_60559_FUNCS_EXT__
# define __STDC_WANT_IEC_60559_FUNCS_EXT__ 1
#endif
#ifndef __STDC_WANT_IEC_60559_TYPES_EXT__
# define __STDC_WANT_IEC_60559_TYPES_EXT__ 1
#endif
#ifndef __STDC_WANT_LIB_EXT2__
# define __STDC_WANT_LIB_EXT2__ 1
#endif
#ifndef __STDC_WANT_MATH_SPEC_FUNCS__
# define __STDC_WANT_MATH_SPEC_FUNCS__ 1
#endif
#ifndef _TANDEM_SOURCE
# define _TANDEM_SOURCE 1
#endif
#ifndef _XOPEN_SOURCE
/* # undef _XOPEN_SOURCE */
#endif

/* Solaris uint typedefs -- not needed on modern systems */
/* #undef _UINT32_T */
/* #undef _UINT64_T */
/* #undef _UINT8_T */

/* --bindir */
#define apl_DIR__bin "/usr/local/bin"

/* --datarootdir */
#define apl_DIR__datarootdir "/usr/local/share"

/* --docdir */
#define apl_DIR__doc "/usr/local/share/doc/GnuAPL"

/* --exec_prefix */
#define apl_DIR__exec_prefix "/usr/local"

/* --libdir */
#define apl_DIR__lib "/usr/local/lib"

/* --localedir */
#define apl_DIR__locale "/usr/local/share/locale"

/* installation directory for GNU APL libraries */
#define apl_DIR__pkglib "/usr/local/lib/apl"

/* --prefix */
#define apl_DIR__prefix "/usr/local"

/* top-level GNU APL source directory */
#define apl_DIR__src "/Users/sparrevo/projects/gnu-apl/src"

/* --sysconfdir */
#define apl_DIR__sysconf "/usr/local/etc"

/* FFT available ? */
#define apl_FFT 1

/* GSL available ? */
#define apl_GSL 0

/* GTK+ version 3 installed ? */
#define apl_GTK3 1

/* GUI (GTK or XCB) available ? */
#define apl_GUI 1

/* PCRE available ? */
#define apl_PCRE 1

/* PNG available ? */
#define apl_PNG 1

/* PostgreSQL code compiled */
#define apl_POSTGRES 1

/* SQLite code compiled */
#define apl_SQLITE3 1

/* Define if compiling for Android */
/* #undef apl_TARGET_ANDROID */

/* Define if building the Erlang interface */
/* #undef apl_TARGET_ERLANG */

/* Define if building libapl.so */
/* #undef apl_TARGET_LIBAPL */

/* Define if building lib_gnu_apl.so */
/* #undef apl_TARGET_PYTHON */

/* X11 is available ? */
#define apl_X11 0

/* XCB is available ? */
#define apl_XCB 0

/* Alt key map profile */
#define cfg_ALT_MAP_WANTED 0

/* APserver listen port name */
#define cfg_APSERVER_PATH "/tmp/GNU-APL/APserver"

/* APserver TCP listen port */
#define cfg_APSERVER_PORT 16366

/* APserver transport: TCP=0, LINUX=1, UNIX=2 */
#define cfg_APSERVER_TRANSPORT 0

/* the desired ASSERT() level (0=no, 1=some, 2=all assertions) */
#define cfg_ASSERT_LEVEL_WANTED 1

/* how cmake was called */
#define cfg_CONFIGURE_ARGS "cmake -S . -B <builddir>"

/* core count */
#define cfg_CORE_COUNT_WANTED 0

/* Define to set options typical for software development */
/* #undef cfg_DEVELOP_WANTED */

/* Define to enable dynamic logging */
/* #undef cfg_DYNAMIC_LOG_WANTED */

/* max. rank of APL values */
#define cfg_MAX_RANK_WANTED 8

/* Define to enable performance counters */
/* #undef cfg_PERFORMANCE_COUNTERS_WANTED */

/* Define to have support for rational numbers (EXPERIMENTAL!) */
/* #undef cfg_RATIONAL_NUMBERS_WANTED */

/* security level */
#define cfg_SECURITY_LEVEL_WANTED 0

/* short value cellcount */
#define cfg_SHORT_VALUE_LENGTH_WANTED 12

/* ./configure with --with-postgresql */
#define cfg_USER_WANTS_POSTGRES 1

/* ./configure with --with-sqlite3 */
#define cfg_USER_WANTS_SQLITE3 1

/* Define to enable internal value checks */
/* #undef cfg_VALUE_CHECK_WANTED */

/* Define to enable value events */
/* #undef cfg_VALUE_HISTORY_WANTED */

/* Define to enable tracing of value flags */
/* #undef cfg_VF_TRACING_WANTED */

/* Define to have visible markers (DONT!) */
/* #undef cfg_VISIBLE_MARKERS_WANTED */

/* Define to make ^D a del-char and ^Z be EOF */
/* #undef cfg_WANT_CTRLD_DEL */
