= Tips for GNU APL Interpreter Designers and Contibutors
//vim: et:ts=4:sw=4:tw=78

:Author: Dr. Jürgen Sauermann, GNU APL

:page-width: 120em
:toc:
:toclevels: 4
:iconsdir: /usr/share/asciidoc/icons
:icons:

== Abstract

This document contains a number of unrelated hints that may be useful to
understanding the GNU APL source code. Its primary purpose is to support
the fading memory of the author, but it may be interesting for others as well.
In addition to the hints there are also a number of rules. These rules
should be observed by those who contribute C/Cpp source code to the
GNU APL project (as opposed to those that contribute APL code).

This document is *NOT* aimed at the normal GNU APL user, i.e. at the APL
programmer. Those users are refered to the various *README* files in the
top-level GNU APL directory.

== The GNU APL Build System

All commands described below shall executed in the top-level GNU APL directory.
The top-level GNU APL directory is the directory that contains - after
unpacking a GNU APL tar file like *apl-1.8.tar.gz* of after fetching the GNU
APL sourced with SVN or with git - the file named *configure.ac*.

GNU APL uses *automake* and *autoconf* to build the interpreter. The build
system performs a number of major steps in typically different places and
by different persons (C/Cpp designer/maintainer vs. user):

=== Step 1: Generate ./configure and a Makefile.in for every Makefile.am

Every directory of the GNU APL source tree contains a file named *Makefile.am*.
The command *autoreconf*, performed in to top-level directory of the GNU APL
source tree:

----
$ autoreconf
----

Command *autoreconf* generates a file named *Makefile.in* for every
*Makefile.am*. In addition it creates a script named *configure*. This
is normally done by the maintainer and the *Makefile.in* files produced
are shipped with GNU APL (tar file or svn/git repository).

The absolute cool thing of *autoconf* (as opposed to e.g. *Cmake* or GUI based
IDEs) is that *autoconf* and *automake* iself need not be installed
by the end users. The *configure* script produced by *autoreconf* is
self-contained and can be executed by the end user in order to configure
different aspects of the GNU APL interpreter. To accommodate this, the
different *Makefile.in* files are shipped with GNU APL even though they
are somewhat redundant (and, compared to the *Makefile.am*, pretty large).

In essence *Makefile.am* files are easy to read and maintain by humans, while
*Makefile.is*  are easy to decode by machines, in particular by the *configure*
script that is produced along with them. In GNU APL the *autoreconf* command
produces a more than 1,000 line top-evel *Makefile.in* from a 150 line
*Makefile.am* and a 25,000 linr ./configures script from its 1,000 line
*configure.ac*

NOTE: If a maintainer adds a new directory to the source tree, then she needs
to add the final *Makefile* in the top-level file *configure.ac* (in m4 macro
*AC_CONFIG_FILES), otherwise the *Makefile.am* will be ignored.

The most important take-away here is that the user or maintainer should never
edit *Makefile*s or *Makefile.in*s because doing so is cumbersome, error-prone,
 and useless because *autoreconf* will overwrite the changes made.

=== Step 2: Generate a Makefile for every Makefile.in

The next step is to run the *configure* script produced in the previous step.
It is performed by the end user (or by the system administrator where
appropriate) in the top-level directory of the GNU APL source tree:

----
$ ./configure
----

The typical end user will run *./configure* without any arguments, while
experts may run it with additional arguments (see README-2-configure
for details). The primary task of *./configure* is to convert every
*Makefile.in* into a corresponding *Makefile*. In doing so, the script tries
to figure which and where the libraries and header files used by GNU APL are
installed on the user's system. The system functions and variables of the
final GNU APL interpreter behaves differently depending on the linraries and
header files present. For example, *⎕FFT* (Fast Fourier Transforms) depends
on library *libfftw3* and if that library(or its header files) are missing
then ⎕FFT will rais a syntax error instead of computing the FFT.

NOTE: On a typical Debian systems, libraries and header files are often
contained in to different packages that should all be installed.

For example, in the ⎕FFT case there are 3 packages:

* libfftw3-bin      # the library itself
* libfftw3-dev      # header files for the library, and
* libfftw3-doc      # documentation related to the library


For ⎕FFT to work the first two are needed and the third does not hurt.
Most of the other libraries follow the same naming scheme for Debian packages.

The configure script produces a lot of output that is useful if a library or
its header file(s) are missing. The final result of the decisions made by
configure is collected in file *config.h* so that the compiler can adapt
itself to the presence or absence of libraries and their header files.

If a library is not detected even though it is installed then either:

* the test performed by ./configure is faulty and then either configure.ac
  or else a more complex test file in subdirectory *m4* need to be fixed, or

* the library only lives in a non-stadard location (e.g. below the user's
  home and then ./configure hopefully provides ./configure option to
  specify that location.

=== Step 3: Compile and Link the GNU APL Interpreter

The final step is to compile the interpreter:
----
$ make
----

The code base is quite large, therefore one may prefer to compile several
source in parallel. For eexample, on an 8 core CPU:

----
make -j 7
----

leaving one core for other purposes. If the compilation is successful then the
interpreter is named *apl* in directory *src*, i.e. *src/apl*. During
development, the interpreter can be started from there without installing it:

----
$ src/apl
-----

After the development is done, the interpreter is installed properly.

NOTE: The steps described only require write permission in and below the
top-level directory, for instance below the user's $HOME directory.
The next step requires write permissions in directories that are normally not
writable by normal users.

=== Step 4: Install the GNU APL Interpreter

Installation of the interpreter must be performed by root:

----
$ sudo make install
----

CAUTION: A common mistake is to try to install the interpreter after the
previous step has failed. The build system will then try to recompile missing
files, but the resulting files will now be owned by root and will no longer be
writable by the user. To fix this:

----
$ sudo chown -R username.username .   # assume user is 'username'
----

The make install installs a few of files (all owned by root, but with read
permissions for everybody):

* The APL interpreter itself in */usr/local/bin/apl*,
* interpreter-related header files */usr/local/include/apl*,
* interpreter-related libraries */usr/local/lib/apl*,
* an info file in */usr/local/share/info/apl.info*,
* a man page in */usr/local/share/man/man1/apl.1*

The default installation prefix */usr/local* can be changed with *./configure*
options.

== Source Code Documentation

GNU APL is fully documented with *Doxygen*. The term *fully* means that every
class member has a (typically rather brief) Doxygen description and *not* that
the description is exhaustive. The purpose is primarily to be a memory aid for
browsing the source code.

The entire *Doxygen* documentation of GNU APL can, provided that *Doxygen*
itself is installed, be produced like this:

----
make DOXY
----

The result are around 6,000 files in directory *html*. After generating them,
the files can be browsed with e.g.

----
firefox html/index.html
----

or with some other browser. The *Doxygen* documentation is a good starting
point for those that want to get a quick overview of the GNU APL source
code.

== Source Code File Types

The *Makefile** files belong to the build system and were explained above.
What remains are:

* C source files (file extension *.c*) are almost never used,
* C header files (file extension *.h*) almost never used, a noteworthy
  exception is *config.h* which is produced by the *./configure* script.
* Cpp source files for inline functions (file extension *.icc*),
* Cpp source files (file extension *.cc*),
* Cpp header files (file extension *.hh*), and
* pure macro files (file extension *.def*).

By and largen, the rules for C and Cpp source and header files are:

* Small and many rather than large and few (aka. modularity). Early versions
  of GNU APL did not follow this rule and some left-overs  still do not (and
  those will be further modularized in the future.
* One class per file; the file name refleccts the class name. Exceptions are
* classes that are closely related (e.g. classes *Token* and *Token_string*)
* The .cc and .hh files names are the same, except for the file name extension
  and classes with a small (say, < 100 lines) source footprint (e.g. those in 
  PrimitiveFunction.hh and PrimitiveFunction.cc).
* Cpp declarations can be made in the .cc file if their scope is local to the
  .cc file (like static declarations in C), otherwise they go into the
corresponding .hh file.

=== .def Files

C/Cpp source file primarily contain C/Cpp code and occasionally declarations.
C/Cpp header files primarily contain C/Cpp declarations and often (inline)
C/Cpp code. In contrast, .def files contain neither C/Cpp code nor
C/Cpp declarations, They only contain macro calls whereby the definition of
the macro is defined outside the .def file. Currently there are about 20 .def
files in the GNU APAL source code so that they deserve an explanation.

==== Why .def Files?

Suppose we have a number of integer error codes:

----
   enum ErrorCode
      {
        NO_ERROR     = 0,
        SYNTAX_ERROR = 1,
        RANK_ERROR   = 2,
        LENGTH_ERROR = 4,
      };
----

Sooner or later we need a string that describes the error in a human readable
format. This requires a mapping between integer error codes and string
literals. There are 2 standard methods in C/C+ to define such a mapping.

==== Method 1: struct definition

----
struct _error_map
{
  ErrorCode ecode;
  const char * ename;
} error_map =
{
  { NO_ERROR,      "OK"           },
  { SYNTAX_ERROR,  "Syntax Error" },
  { RANK_ERROR,    "Rank Error"   },
  { LENGTH_ERROR,  "Length Error" },
};

const char *
get_error_string(ErrorCode ec)
{
   return error_map[ec];
}
----

==== Method 2: switch statement

----
const char *
get_error_string(ErrorCode ec)
{
   switch(ec)
      {
        case NO_ERROR:      return "OK";
        case SYNTAX_ERROR:  return "Syntax Error";
        case RANK_ERROR:    return "Rank Error";
        case LENGTH_ERROR:  return "Length Error";
      }
   return "Unknown error";
}
----

Now suppose we add another ErrorCode *DOMAIN_ERROR* to the *enum ErrorCode*.
Suppose further that we add the new error code to the enum but not to the
*get_error_string()* function. This is a fairly common mistake, in particular
because *ErrorCode* is usually declared in a *.hh* file and
*get_error_string()* is defined in the corresponding *.cc* file. In that case
Method 1 will most likely produce a sagmentation fault at runtime, which is
about the worst case that may happen. <ethod 2 is a little better because a
smart compiler like g++ will issue a warning in this case. Both methods are,
however, quite inconvenient for the C/Cpp programmer, in particular if many
such mappings are needed in a larger program.

In GNU APL this problem is solved in the following way:

* #define a macro that expresses the relationship (between integer error codes
  and pass:[C/Cpp] literals for the corresponding error text in our example),
  and
* call that macro, typically in sevseral different files with the macro
  defined differently. Calling the macro is performed by \#including the .def
  file. In our example:

In e.g. *errors.def*:
----
   error_def(
   error_def(NO_ERROR     , 0, OK           )
   error_def(SYNTAX_ERROR , 1, Syntax Error )
   error_def(RANK_ERROR:    2, Rank Error   )
   error_def(LENGTH_ERROR:  3, Length Error )

#undef error_def   /* as to detect missing definitions of the error_def()
macro */
----

In, say, *errors.hh*:

----
   enum ErrorCode
      {
#define error_def(enum_name, enum_value, _error_string) \
   enum_name = enum_value,
#include "errors.def"
      };
----

And finally in *errors.cc*:

----
const char *
get_error_string(ErrorCode ec)
{
   switch(ec)
      {
#define error_def(enum_name, _enum_value, error_string) \
   case enum_name: return #error_string;
#include "errors.def"
      }
   return "Unknown error";
}
----

Note the following:

* the macro invocations of *error_def()* (in the *.def* file) have more
  arguments than are used in their macro definitions (in the *.hh* or *.cc*
  files). GNU APL has a naming convention that unused macro arguments of
  macros (which are typical for the *.cc* and *.hh*  files) start with
  underscore (_). For this reason the argument lists of the #defines above
  differ slightly.
* *error_string* is not quoted in *errors.def* even though *get_error_string()*
  returns a const char *. The quoting is performed by \# in #error_string
 (a preprocessor feature).
* the example above uses a simple 1:1 relation between two types. Some *.def*
  files use more than two sides, e.g. numeric IDs, string names, and help
  texts.

=== Rules for .def Files

* The *.def* file should *#undef* all macros that it uses. This is a safeguard
  against forgetting to *#define* a macro before #including the *.def* file
  (this may or may not be detectable by the compiler).
* A *.def* file should normally not use more than one macro. An exception
  occurs when  macros are very similar (e.g. SystemVariable.def with macro
* ro_sv_def* (for read-only system variables), *rw_sv_def* (for read/write
  system variables), and *sf_def* for system functions).
* item separators such as , in enums or ; in case statements are contained in
  the macro definitions (i.e. in the *.hh* or *.cc* file) and not in the macro
  call (i.e. not in the *.def* file). This is because the separators may differ
  for different macros.

The most important take-away here are:

* *.def* files contain only macro invocations,
* *.def* files are #included in several files and almost certainly the macro
   definitions (before #including a *.def* file) differ between the files,
* the macros are #defined outside the *.def* file but #undef'ed inside the
  *.def* file. (This is normally a bad programming practice, but on purpose
  here).

== Coding Style

GNU APL is a GNU project. For the most part it therefore follows the GNU
coding standard, see: https://www.gnu.org/prep/standards/standards.html
With some minor deviations as to further improve the readability of the C/Cpp
code.

=== General

* keep lines short (≤ 78 characters) where possible
* NEVER use tabs (ASCII 0x09) in the source code

=== Indentatation and Blanks

==== Function bodies (.cc files)

* Variable declarations at top-level scope are not indented:
* Cpp code at the top-level scope are indented with 3 blanks:

----
void
foo()
{
int x = 0;            // declaration: not indented!

   printf("%d:, x);   // code: indented by 3 spaces

int y = 1;            // another declaration.
   ...
}
----

* Variable declarations below top-level scope are indented with 2 (from the {
  starting the scope
* Cpp code below the top-level scope are also indented with 2 blanks:

----
void
foo()
{
int x = 0;         // declaration: not indented!
int y = 1;         // another declaration.

   if (x)
      {                               // start of sub-scope
        printf("positive x=%d", x);   // code: indented by 2 spaces
      }
   else
      {                               // start of another sub-scope
        printf("zero x");             // code: indented by 2 spaces
      }
}
----

==== Conditionals

* conditionals are not functions! put 1 blank between the keyword and the
  condition
* the body of the conditional is indented according to the opening ( of the
  condition (for short ones like if, else, or for), but no more than 2 blanks:

----
void
foo()
{
int x = 0;

   // DO NOT:
   if(i == 0)

   // DO:
   if (i == 0)
      {
        ...
      }

   for (int i = 0; i < N; ++i)
       {
         ...
       }

   while (i == 0)
      {
        ...
      }
}
----

* you MAY put single statements or very short bodies onto the condition line,
* but NOT mix single- and multi-line styles for *if* and *else* clauses, and
* place the { and } of multi-line bodies on the same column, that is:
* you MUST NEVER NEVER NEVER use K&R style:

----
   // DO:

   if (x >= 0)   return "positive";
   else          return "negative";

   // DO NOT:

   if (x >= 0)   { return "positive"; }   // redundant { }
   else          { return "negative"; }   // redundant { }

   if (x >= 0)   return "positive";   // single-line style
   else                               // multi-line style
      {
        error = true;
        returr "negative";
      }

   // HEAVEN FORBID (aka. K&R style)
   if (x >= 0) {
      return "positive";
   } else {
      return "negative";
   }
----
==== Function arguments

* one blank after every comma and between token:

----
   // DO:

int
main(int argc, char * argv[])
{
   ...
}

   // DO NOT ANY OF THE FOLLOWING...

int
main (int argc, char * argv[])   // extra space before arguments
{
   ...
}

int
main( int argc, char * argv[] )   // extra spaces around arguments
{
   ...
}

int
main(int argc, char *argv[])   // no space after *
{
   ...
}

int
main(int argc, char* argv[])   // no space before *
{
   ...
}
----

==== Class declarations (.hh files)

To the extent possible:

* declare public members (= the external interface) before protected
  members (= the class implementation),
* declare members before static members,
* declare member funtions before fsts mrmbers,
* keep the following declaration order:
** constructors,
** destructor,
** inline functions,
** non-inline functions
* always use *protected:* rather than *private:* for the members of a class.
  GNU APL uses the convention that *private:* members are used to prevent the
  accidental function calls that are sometimes generated by the Cpp compiler
  (implicit conversion). In GNU APL, such members are declared, but not
  defined (so that the linker will complain if the compiler should generate
  them).

Indentation:

* indent all members with 2 spaces,
* indent inline function bodies by 3 more spaces
* do this recursively (nested classes)

And finally: have a look at the existing *.cc* and *.hh* files. Even though
this will cause some extra work on your part, it simplifies the reading of
your code for many others. A project with different styles in different files
looks rather unprofessional, so please respect the style rules above even if
you do not like them.

