#!/bin/bash
# Companion shell script for APnnn.tc: starts a secondary APL interpreter
# with --id 1011 that communicates with the primary (--id 1010) via VAR444.
# Generated by cmake; do not edit — edit APnnn_1011.sh.in instead.

APL="/Users/sparrevo/projects/gnu-apl/ts/src/apl"
TC2="/Users/sparrevo/projects/gnu-apl/ts/testcases/APnnn_1011.tc2"

"$APL" --id 1011 --noCONT -f "$TC2" </dev/null >/dev/null 2>&1 &
