# cmake/AplConfigSummary.cmake
# Prints a configuration summary analogous to the Autotools summary.

message(STATUS "")
message(STATUS "---- GNU APL ${PROJECT_VERSION} configuration summary ----")
message(STATUS "")
message(STATUS "  Install prefix:              ${CMAKE_INSTALL_PREFIX}")
message(STATUS "  Build type:                  ${CMAKE_BUILD_TYPE}")
message(STATUS "  C++ compiler:                ${CMAKE_CXX_COMPILER}")
message(STATUS "  C++ standard:                ${CMAKE_CXX_STANDARD}")
message(STATUS "")
message(STATUS "  Optional libraries")
message(STATUS "    APL_WITH_OPTIONAL_LIBS:    ${APL_WITH_OPTIONAL_LIBS}")
message(STATUS "    apl_FFT   (⎕FFT):         ${apl_FFT}")
message(STATUS "    apl_GSL   (⎕MX):          ${apl_GSL}")
message(STATUS "    apl_PCRE  (⎕RE):          ${apl_PCRE}")
message(STATUS "    apl_PNG   (⎕PNG):         ${apl_PNG}")
message(STATUS "    apl_SQLITE3  (⎕SQL):      ${apl_SQLITE3}")
message(STATUS "    apl_POSTGRES (⎕SQL):      ${apl_POSTGRES}")
message(STATUS "    apl_GTK3  (⎕GTK/⎕PLOT):  ${apl_GTK3}")
message(STATUS "    apl_XCB   (⎕PLOT):        ${apl_XCB}")
message(STATUS "    apl_GUI   (GTK3|XCB):     ${apl_GUI}")
message(STATUS "")
message(STATUS "  Build targets")
message(STATUS "    Executable:                ${APL_EXECUTABLE_NAME}")
message(STATUS "    apl_TARGET_ANDROID:        ${APL_WITH_ANDROID}")
message(STATUS "    apl_TARGET_ERLANG:         ${APL_WITH_ERLANG}")
message(STATUS "    apl_TARGET_LIBAPL:         ${APL_WITH_LIBAPL}")
message(STATUS "    apl_TARGET_PYTHON:         ${APL_WITH_PYTHON}")
message(STATUS "")
message(STATUS "  Development options")
message(STATUS "    APL_DEVELOP:               ${APL_DEVELOP}")
message(STATUS "    APL_ASSERT_LEVEL:          ${APL_ASSERT_LEVEL}")
message(STATUS "    APL_MAX_RANK:              ${APL_MAX_RANK}")
message(STATUS "    APL_DYNAMIC_LOG:           ${APL_DYNAMIC_LOG}")
message(STATUS "    APL_PERFORMANCE_COUNTERS:  ${APL_PERFORMANCE_COUNTERS}")
message(STATUS "    APL_VALUE_CHECK:           ${APL_VALUE_CHECK}")
message(STATUS "    APL_VALUE_HISTORY:         ${APL_VALUE_HISTORY}")
message(STATUS "    APL_RATIONAL_NUMBERS:      ${APL_RATIONAL_NUMBERS}")
message(STATUS "    APL_CXX_WERROR:            ${APL_CXX_WERROR}")
message(STATUS "    APL_GPROF:                 ${APL_GPROF}")
message(STATUS "    APL_GCOV:                  ${APL_GCOV}")
message(STATUS "")
message(STATUS "  APserver")
message(STATUS "    Transport:                 ${APL_APSERVER_TRANSPORT} (${_cfg_APSERVER_TRANSPORT})")
message(STATUS "    Port:                      ${APL_APSERVER_PORT}")
message(STATUS "    Path:                      ${APL_APSERVER_PATH}")
message(STATUS "")
